FROM golang:1.9-alpine as builder
RUN apk add --update --no-cache curl
RUN go build -o dist/voyager/voyager-alpine-amd64 *.go
RUN curl -fsSL -o hack/docker/voyager/auth-request.lua https://raw.githubusercontent.com/appscode/haproxy-auth-request/v1.8.12/auth-request.lua

FROM haproxy:1.8.12-alpine

RUN set -x \
  && apk add --update --no-cache ca-certificates lua5.3 lua-socket \
  && ln -sf /usr/share/lua/ /usr/local/share/ \
  && ln -sf /usr/lib/lua/ /usr/local/lib/

COPY auth-request.lua /etc/auth-request.lua
COPY templates /srv/voyager/templates/
COPY dist/voyager/voyager-alpine-amd64 /usr/bin/voyager

# https://github.com/appscode/voyager/pull/1038
COPY test.pem /etc/ssl/private/haproxy/tls/test.pem
COPY errorfiles /srv/voyager/errorfiles/

ENTRYPOINT ["voyager"]
